# == Schema Information
#
# Table name: claims_data
#
#  id                                                :integer       not null, primary key
#  heig_height                                       :integer       
#  weig_weight                                       :integer       
#  bmi_body_mass_index                               :integer       
#  waist_waist_circumference                         :integer       
#  smok_smoking_history                              :string(20)    
#  diab_type_of_diabetes                             :string(18)    
#  yodd_year_of_diabetes_diagnosis                   :integer       
#  hoac_history_of_acute_coronary_syndrome           :string(18)    
#  angi_angina_ami                                   :string(18)    
#  ptca_ptca_cabg                                    :string(18)    
#  tia_stroke_tia                                    :string(18)    
#  pvd_peripheral_vessel_disease                     :string(18)    
#  fhcvd_family_history_early_cardiovascular_disease :string(18)    
#  gld_genetic_lipid_disorder                        :string(40)    
#  renal_established_renal_disease                   :string(18)    
#  atfi_atrial_fibrillation                          :string(18)    
#  mets_diagnosed_metabolic_syndrome                 :string(18)    
#  preg_pregnant                                     :string(18)    
#  sbp_systolic_blood_pressure                       :integer       
#  dbp_diastolic_blood_pressure                      :integer       
#  sbpp_systolic_blood_pressure_previous             :integer       
#  dbpp_diastolic_blood_pressure_previous            :integer       
#  cvdr_cvd_risk                                     :decimal(8, 2) 
#  gluc_fasting_glucose                              :decimal(8, 2) 
#  tc_total_cholesterol                              :decimal(8, 2) 
#  hdl_hdl_cholesterol                               :decimal(8, 2) 
#  ldl_ldl_cholesterol                               :decimal(8, 2) 
#  trig_triglyceride                                 :decimal(8, 2) 
#  tchdl_tc_hdl_ratio                                :decimal(8, 2) 
#  creat_serum_creatinine                            :decimal(8, 2) 
#  egfr_glumeral_filtration                          :string(18)    
#  acr_urine_albumin_to_creatine_ratio               :decimal(8, 2) 
#  dsma_dipstick_test_for_microalbuminuria           :string(18)    
#  apst_albumin_protein_stick_test                   :string(18)    
#  hba1c_hba1c                                       :decimal(8, 2) 
#  retind_date_last_retinal_screening                :datetime      
#  retini_retinal_screening_interval                 :string(18)    
#  aspi_aspirin                                      :string(18)    
#  clop_clopidogrel                                  :string(18)    
#  warf_warfarin                                     :string(18)    
#  acei_ace_inhibitor                                :string(18)    
#  a2ra_a2_receptor_antagonist                       :string(18)    
#  beta_beta_blocker                                 :string(18)    
#  thia_thiazide                                     :string(18)    
#  caan_calcium_antagonist                           :string(18)    
#  oahm_other_anti_hypertensive_medication           :string(18)    
#  statin_statin                                     :string(18)    
#  fibra_fibrate                                     :string(18)    
#  ollm_other_lipid_lowering_medication              :string(18)    
#  nirt_nicotine_replacement_therapy                 :string(18)    
#  lifet_lifestyle_therapy                           :string(18)    
#  green_green_prescription                          :string(18)    
#  insu_insulin                                      :string(18)    
#  metf_metformin                                    :string(18)    
#  sulp_sulphonylurea                                :string(18)    
#  glit_glitazone                                    :string(18)    
#  acar_acarbose                                     :string(18)    
#  eyer_eye_referral_today                           :string(18)    
#  vacl_visual_acuity_left                           :string(18)    
#  vacr_visual_acuity_right                          :string(18)    
#  retwe_retinopathy_worst_eye                       :string(18)    
#  macwe_maculopathy_worst_eye                       :string(18)    
#  feets_feet_sensation                              :string(18)    
#  feetc_feet_circulation                            :string(18)    
#  hdfu_history_diabetic_foot_ulcer                  :string(18)    
#  cdfu_current_diabetic_foot_ulcer                  :string(18)    
#  ohrf_other_criteria_for_high_risk_foot            :string(18)    
#  plla_previous_diabetic_lower_limb_amputation      :string(18)    
#  hypoa_hypoglycaemic_attacks                       :string(18)    
#  bgsm_blood_glucose_self_monitoring                :string(18)    
#  refto_Referral_To                                 :string(28)    
#  exahos_exacarbation_hospital_admit                :string(18)    
#  exaevi_exacarbation_emergency_visit               :string(18)    
#  exaost_exacarbation_oral_steriod                  :string(18)    
#  inhtec_inhaler_technique                          :string(18)    
#  medcon_medical_concordance                        :string(18)    
#  symnig_symptoms_night                             :string(18)    
#  symday_symptoms_day                               :string(18)    
#  actlim_activity_limitations                       :string(18)    
#  actplan_action_plan                               :string(18)    
#  saba_short_acting_bronchodilator                  :string(36)    
#  sabause_short_acting_ba_usage                     :string(18)    
#  ics_inhaled_corticosteroid                        :string(36)    
#  laba_long_acting_bronchodilator                   :string(36)    
#  pfmeter_peak_flow_meter                           :string(18)    
#  a3lm_asthma_3rd_line_medication                   :string(36)    
#  pefr_peak_expiratory_flow_rate                    :integer       
#  pefrpb_pefr_post_bronchodilator                   :integer       
#  pefrpbip_pefr_post_bronch_improve_per             :integer       
#  pefrhig_pefr_highest                              :integer       
#  pefrlow_pefr_lowest                               :integer       
#  pefrvar_pefr_variability                          :integer       
#  pefrpred_pefr_predicted                           :integer       
#  pefrppred_pefr_percentage_predicted               :integer       
#  fev1_forced_expiratory_volume                     :decimal(8, 2) 
#  fev1pred_fev1_predicted                           :decimal(8, 2) 
#  fev1ppred_fev1_percentage_predicted               :integer       
#  fvc_forced_vital_capacity                         :decimal(8, 2) 
#  fev1fvcr_fev1_fvc_ratio                           :integer       
#  agea_age_of_asthma_diagnosis                      :integer       
#  smpy_smoking_pack_years                           :integer       
#  fvcpred_fvc_predicted                             :decimal(8, 2) 
#  fvcppred_fvc_percentage_predicted                 :integer       
#  chqin_child_heath_q_interpretation                :string(28)    
#  chqre_child_heath_q_referral                      :string(28)    
#  chqres_child_heath_q_referral_status              :string(18)    
#  imm4ud_4y_immunisation_up_to_date                 :string(18)    
#  immvt_immunisation_vacc_today                     :string(18)    
#  immre_immunisation_referral                       :string(28)    
#  immres_immunisation_referral_status               :string(18)    
#  growin_growth_measure_interpretation              :string(28)    
#  growre_growth_measure_referral                    :string(28)    
#  growres_growth_measure_referral_status            :string(18)    
#  dentde_dental_decay                               :string(18)    
#  denten_dental_enrolled                            :string(18)    
#  dentent_dental_enrolled_today                     :string(18)    
#  dentin_dental_interpretation                      :string(28)    
#  dentre_dental_referral                            :string(28)    
#  dentres_dental_referral_status                    :string(18)    
#  vishs_vision_hearing_status                       :string(18)    
#  vishr_vision_hearing_referral                     :string(28)    
#  vishrs_vision_hearing_referral_status             :string(18)    
#  pedsss_peds_significant_score                     :integer       
#  pedsns_peds_non_significant_score                 :integer       
#  pedsin_peds_interpretation                        :string(28)    
#  pedsref_peds_referral                             :string(28)    
#  pedsrefs_peds_referral_status                     :string(18)    
#  sdqess_sdq_emotional_symptoms_score               :integer       
#  sdqcps_sdq_conduct_problems_score                 :integer       
#  sdqhys_sdq_hyperactivity_score                    :integer       
#  sdqpps_sdq_peer_problems_score                    :integer       
#  sdqtds_sdq_total_difficulties_score               :integer       
#  sdqpbs_sdq_prosocial_behaviour_score              :integer       
#  sdqin_sdq_interpretation                          :string(28)    
#  sdqref_sdq_referral                               :string(28)    
#  sdqrefs_sdq_referral_status                       :string(18)    
#  pedsref2_peds_referral_2                          :string(28)    
#  pedsref2s_peds_referral_2_status                  :string(18)    
#  sdqref2_sdq_referral_2                            :string(28)    
#  sdqref2s_sdq_referral_2_status                    :string(18)    
#  nokrel_nok_relationship                           :string(18)    
#  nokgn_nok_given_names                             :string(18)    
#  nokfn_nok_family_name                             :string(18)    
#  notes_notes                                       :string(28)    
#  mhdx_mhealth_diagnosis                            :string(18)    
#  mhdx2_mhealth_diagnosis_2                         :string(18)    
#  mhdx3_mhealth_diagnosis_3                         :string(18)    
#  como_co_morbidities                               :string(36)    
#  qolr_quality_of_life_rating                       :string(5)     
#  copa_co_payment_amount                            :decimal(8, 2) 
#  oorm_other_oral_medication                        :string(18)    
#  omed_other_medication                             :string(18)    
#  pctd_positive_changes_to_diet                     :string(18)    
#  pcte_positive_changes_to_excercise                :string(18)    
#  slty_skin_lesion_type                             :string(35)    
#  sllo_skin_lesion_location                         :string(38)    
#  slex_skin_lesion_excision                         :string(18)    
#  cpet_care_plus_enrolment_type                     :string(18)    
#  vhsr_visit_health_status_reviewed                 :boolean       
#  vcpr_visit_care_plan_reviewed                     :boolean       
#  vcpr_visit_crisis_plan_reviewed                   :boolean       
#  vped_visit_patient_education                      :boolean       
#  vrxr_visit_medication_review                      :boolean       
#  vpgr_visit_patient_goals_reviewed                 :boolean       
#  cpdr_care_plus_disenrolment_reason                :string(28)    
#  mhaod_mhealth_contract_alcohol_other_drug         :boolean       
#  mhmoh_mhealth_contract_ministry_of_health         :boolean       
#  mhmsd_mhealth_contract_ministry_of_social_dev     :boolean       
#  mhapt_mhealth_appointment_type                    :string(18)    
#  refft_referral_from_type                          :string(28)    
#  reffn_referral_from_name                          :string(18)    
#  refda_date_of_referral                            :datetime      
#  mhatt_mhealth_attendance_type                     :string(18)    
#  mhost_mhealth_one_off_session_type                :string(18)    
#  reftt_referral_to_type                            :string(28)    
#  reftn_referral_to_name                            :string(18)    
#  refto_referral_to_other                           :string(18)    
#  mhsty_mhealth_session_type                        :string(18)    
#  mhk10_mhealth_kessler_10                          :string(4)     
#  mhkde_mhealth_kessler_10_declined                 :boolean       
#  comor_co_morbidities_read                         :string(8)     
#  comor2_co_morbidities_read_2                      :string(8)     
#  btwc_barriers_to_work_code                        :string(4)     
#  btwc2_barriers_to_work_code_2                     :string(4)     
#  btwc3_barriers_to_work_code_3                     :string(4)     
#  btwc4_barriers_to_work_code_4                     :string(4)     
#  mhex_mhealth_exit_reason                          :string(28)    
#  taoby_taxi_ordered_by                             :string(18)    
#  tapos_taxi_position                               :string(18)    
#  tapur_taxi_purpose                                :string(28)    
#  tapuo_taxi_purpose_other                          :string(18)    
#  coora_contraception_oral                          :boolean       
#  coecp_contraception_ecp                           :boolean       
#  codep_contraception_depo_provera                  :boolean       
#  coiucd_contraception_iucd                         :boolean       
#  cocon_contraception_condom                        :boolean       
#  codia_contraception_diaphragm                     :boolean       
#  cooth_contraception_other                         :boolean       
#  stichl_sti_chlamydia                              :boolean       
#  stihpv_sti_hpv_warts                              :boolean       
#  stihsv_sti_hsv_herpes                             :boolean       
#  stigon_sti_gonorrhoea                             :boolean       
#  stinsu_sti_nsu                                    :boolean       
#  stioth_sti_other                                  :boolean       
#  shoadv_shealth_advice                             :boolean       
#  shopgt_shealth_pregnancy_test                     :boolean       
#  shotop_shealth_top_referral                       :boolean       
#  shooth_shealth_other                              :boolean       
#  hcra_hcheck_referring_agency                      :string(28)    
#  canex_nutrition_exercise                          :boolean       
#  casmk_smoking                                     :boolean       
#  cacvdr_cvd_risk                                   :boolean       
#  cadiab_diabetes_management                        :boolean       
#  cabre_breast_health                               :boolean       
#  cacxs_cervical_screening                          :boolean       
#  casxh_sexual_health                               :boolean       
#  caohn_other_heath_need                            :boolean       
#  cond_condition                                    :string(28)    
#  conr_condition_read                               :string(8)     
#  dod_date_of_death                                 :datetime      
#  camedi_medications                                :boolean       
#  mhphq9_mhealth_phq_9                              :string(2)     
#  mhdx4_mhealth_diagnosis_4                         :string(18)    
#  mhdx5_mhealth_diagnosis_5                         :string(18)    
#  mhdx6_mhealth_diagnosis_6                         :string(18)    
#  canut_nutrition                                   :boolean       
#  chqred_child_heath_q_referral_date                :datetime      
#  immred_immunisation_referral_date                 :datetime      
#  growred_growth_measure_referral_date              :datetime      
#  dentred_dental_referral_date                      :datetime      
#  vishrd_vision_hearing_referral_date               :datetime      
#  pedsrefd_peds_referral_date                       :datetime      
#  sdqrefd_sdq_referral_date                         :datetime      
#  pedsref2d_peds_referral_2_date                    :datetime      
#  sdqref2d_sdq_referral_2_date                      :datetime      
#  smready_smoking_readiness_quit                    :string(32)    
#  smhou_smoking_household                           :string(32)    
#  smref_smoking_action_referral                     :string(32)    
#  smpatrx_smoking_patch_rx                          :string(18)    
#  smgumrx_smoking_gum_rx                            :string(18)    
#  smothrx_smoking_other_rx                          :string(28)    
#  smquit_smoking_quit_status                        :string(32)    
#  diabscm_diabetes_self_care_measure                :integer       
#  supatt_support_person_attending                   :integer       
#  ndxdiab_newly_dx_diabetes                         :integer       
#  hovi_home_visit                                   :string(8)     
#  rtow_return_to_work                               :string(18)    
#  prov_providers_name                               :string(18)    
#  nosess_number_of_sessions                         :integer       
#  sdqtc_sdq_t_completed                             :string(18)    
#  nokst_nok_street                                  :string(30)    
#  noksu_nok_suburb                                  :string(20)    
#  noksu_nok_city                                    :string(20)    
#  nokph_nok_phone                                   :string(14)    
#  nokce_nok_cell_phone                              :string(14)    
#  sdqtcec_sqd_t_ece                                 :string(28)    
#  smoc_smoking_outcome                              :string(32)    
#  hayf_hay_fever                                    :boolean       
#  hypv_hyperventilation                             :boolean       
#  gord_gastro_oesophageal_reflux                    :boolean       
#  rhin_rhinitis                                     :boolean       
#  ecze_eczema                                       :boolean       
#  trgemo_trigger_emotions                           :boolean       
#  trgani_trigger_animals                            :boolean       
#  trgexe_trigger_exercise                           :boolean       
#  trgfdr_trigger_food_drink                         :boolean       
#  trgres_trigger_respiratory_infection              :boolean       
#  trgasp_trigger_aspirin                            :boolean       
#  trgocc_trigger_occupational                       :boolean       
#  trghor_trigger_hormonal                           :boolean       
#  trgcai_trigger_cold_air                           :boolean       
#  trgdus_trigger_dust                               :boolean       
#  icsuse_ics_usage                                  :string(8)     
#  infvac_influenza_vacc_given                       :string(8)     
#  slbt_skin_lesion_benign_type                      :string(35)    
#  rfiskc_foot_risk_category                         :string(26)    
#  podref_podiatary_referral                         :string(26)    
#  podref_podiatary_referral2                        :string(26)    
#  ohyp_other_hypoglycaemic_medication               :string(18)    
#  podr_podiatry_referral_today                      :string(18)    
#  alus_alcohol_under_surveillance                   :string(8)     
#  alfq_alcohol_frequency                            :string(24)    
#  alds_alcohol_drinks_per_session                   :integer       
#  albf_alcohol_binge_frequency                      :string(18)    
#  dcsa_drink_check_section_a                        :integer       
#  dcsb_drink_check_section_b                        :integer       
#  dcsc_drink_check_section_c                        :integer       
#  alrc_alcohol_readiness_to_change                  :string(18)    
#  alag_alcohol_advice_given                         :string(8)     
#  noga_number_of_group_attendances                  :integer       
#  nopga_number_of_partner_group_attendances         :integer       
#  pnrt_pnap_referral_to                             :string(48)    
#  pnrt2_pnap_referral_to_2                          :string(48)    
#  epdssc_epds_score                                 :integer       
#  epds10_epds_self_harm                             :integer       
#  mhgad7_mhealth_gad_7                              :integer       
#  etcon_e_therapy_condition                         :string(18)    
#  mhth_mh_therapy                                   :string(18)    
#  pedsqv_peds_question_values                       :string(20)    
#  sdqqv_sdq_question_values                         :string(50)    
#  prio_priority_level                               :string(30)    
#  cont_contact_type                                 :string(32)    
#  conl_contact_location                             :string(28)    
#  demen_dementia                                    :string(18)    
#  ds01_date_service_01                              :datetime      
#  ds02_date_service_02                              :datetime      
#  ds03_date_service_03                              :datetime      
#  ds04_date_service_04                              :datetime      
#  ds05_date_service_05                              :datetime      
#  ds06_date_service_06                              :datetime      
#  ds07_date_service_07                              :datetime      
#  ds08_date_service_08                              :datetime      
#  ds09_date_service_09                              :datetime      
#  ds10_date_service_10                              :datetime      
#  ds11_date_service_11                              :datetime      
#  trgmold_trigger_mould_damp                        :boolean       
#  fhato_fh_atopy                                    :boolean       
#  sinu_sinusitis                                    :boolean       
#  abass_abuse_assessment                            :string(32)    
#  abinc_abuse_screen_incomplete                     :string(32)    
#  abmen_abuse_mental                                :string(28)    
#  abphy_abuse_physical                              :string(28)    
#  absex_abuse_sexual                                :string(28)    
#  abneg_abuse_neglect                               :string(28)    
#  acc_acc_accident                                  :string(18)    
#  advg_advice_info_given                            :string(28)    
#  maosu_maori_support                               :string(28)    
#  abvho_abuse_present_at_home                       :string(18)    
#  abunc_abuse_uncorroborated_history                :string(18)    
#  abcyf_abuse_ho_cyfs_engagement                    :string(18)    
#  abdel_abuse_delay_medical_advice                  :string(18)    
#  abtra_abuse_history_trauma                        :string(18)    
#  abvhi_abuse_changing_history                      :string(18)    
#  abcdr_abuse_changing_dr                           :string(18)    
#  abgus_abuse_gastrourinary_sx                      :string(18)    
#  refts_referral_to_status                          :string(18)    
#  provt_provider_type                               :string(18)    
#  km_kilometeres                                    :integer       
#  ihd_heart_disease                                 :string(18)    
#  resp_respiratory_illnesses                        :string(18)    
#  nurref_nutritionist_referral                      :string(18)    
#  reas_reason                                       :string(18)    
#  treat_treatment                                   :string(18)    
#  vono_voucher_no                                   :string(18)    
#  alcs_alcohol_consumption                          :string(18)    
#  alar_alcohol_at_risk                              :string(18)    
#  mhswk_mhealth_contract_social_worker              :boolean       
#  accd_acc_accident_date                            :datetime      
#  amgmt_under_active_mgmt                           :boolean       
#


class ClaimsData < ActiveRecord::Base
  set_table_name 'claims_data'
  
end
